- name: Helm
  hosts: all
  gather_facts: true
  vars_files:
    - ../vars/main.yml

  tasks:
  # Installation
  # curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  - name: Installation
    tags: [init, update]
    ansible.builtin.include_tasks:
      file: ../tasks/script.yml
    vars:
      url: "{{ helm_install_url }}"
      cmd: /bin/bash -c /tmp/install.sh

  # Version
  - name: Version
    tags: [init, update]
    ansible.builtin.include_tasks:
      file: ../tasks/version.yml
    vars:
      cmd: helm version

  # Plugins
  - name: Plugins
    block:

    - name: Install plugins
      tags: init
      kubernetes.core.helm_plugin:
        plugin_path: "{{ item }}"
        state: present
      loop: "{{ helm_plugin_urls }}"

    - name: Upgrade plugins
      tags: update
      kubernetes.core.helm_plugin:
        plugin_name: "{{ item }}"
        state: latest
      loop: "{{ helm_plugin_names }}"

    always:
    - name: Confirm plugins
      tags: [init, update]
      ansible.builtin.command:
        cmd: helm plugin list
      register: plugins_list
      changed_when: false

    - name: Show plugins
      tags: [init, update]
      when: plugins_list is defined
      ansible.builtin.debug:
        msg: "Installed plugins: {{ plugins_list.stdout }}"

  # Formulas
  - name: Formulas
    tags: [init, update]
    ansible.builtin.include_tasks:
      file: ../tasks/formulas.yml
    vars:
      formulas: "{{ helm_formulas }}"
