- name: Docker Images
  hosts: all
  gather_facts: false
  vars_files:
    - ../vars/main.yml

  tasks:
  # Pull
  - name: Pull
    tags: init
    block:

    - name: List images
      ansible.builtin.debug:
        msg: "images: {{ docker_images }}"

    - name: Pull default images
      community.docker.docker_image:
        name: "{{ item }}"
        source: pull
        pull:
          platform: amd64
        state: present
      loop: "{{ docker_images }}"
