- name: Kubernetes
  hosts: all
  gather_facts: true
  vars:
    formulas:
      - helmfile
      - kubectx
      - k9s
      - stern
    helm_install_tmp: /tmp/helm
    helm_install_url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    kubectl_install_tmp: /tmp/kubernetes
  vars_files:
    - ../vars/main.yml

  tasks:
  # Aliases collection from https://github.com/ahmetb/kubectl-aliases
  - name: Aliases
    tags: [init, update]
    block:

    - name: Create .kube directory
      ansible.builtin.file:
        path: "/home/ubuntu/.kube"
        state: directory
        mode: 0755
        owner: ubuntu
        group: ubuntu

    - name: Download aliases
      ansible.builtin.uri:
        method: GET
        url: https://raw.githubusercontent.com/ahmetb/kubectl-aliases/master/.kubectl_aliases
        dest: /home/ubuntu/.kube/aliases.sh
        owner: ubuntu
        group: ubuntu
        follow_redirects: safe
        mode: 0700

    - name : Update aliases
      ansible.builtin.replace:
        path: /home/ubuntu/.kube/aliases.sh
        regexp: kubectl
        replace: kctl

  # Kubectl
  - name: kubectl
    tags: [init, update]
    block:

    - name: kubectl - Create temporary directory
      ansible.builtin.file:
        path: "{{ kubectl_install_tmp }}"
        state: directory
        mode: 0700

    - name: kubectl - Get latest version
      ansible.builtin.uri:
        url: https://dl.k8s.io/release/stable.txt
        return_content: yes
      register: version

    - name: kubectl - Download
      ansible.builtin.uri:
        method: GET
        url: https://dl.k8s.io/release/{{ version.content }}/bin/{{ ansible_system | lower }}/{{ deb_architecture[ansible_architecture] }}/kubectl
        follow_redirects: safe
        dest: "{{ kubectl_install_tmp }}/kubectl"

    - name: kubectl - Get checksum
      ansible.builtin.shell: # using shell to support "|"
        cmd: sha256sum {{ kubectl_install_tmp }}/kubectl | cut -d " " -f1
      register: checksum

    - name: kubectl - Download control checksum
      ansible.builtin.uri:
        method: GET
        url: https://dl.k8s.io/release/{{ version.content }}/bin/{{ ansible_system | lower }}/{{ deb_architecture[ansible_architecture] }}/kubectl.sha256
        follow_redirects: safe
        dest: "{{ kubectl_install_tmp }}/kubectl.sha256"

    - name: kubectl - Get control checksum
      ansible.builtin.command:
        cmd: cat {{ kubectl_install_tmp }}/kubectl.sha256
      register: control_checksum

    - name: kubectl - Verify checksum
      ansible.builtin.assert:
        that:
          - checksum.stdout == control_checksum.stdout
        fail_msg: "checksum verification failed"
        success_msg: "checksum verified"

    - name: kubectl - Copy file with owner and permissions
      ansible.builtin.copy:
        src: "{{ kubectl_install_tmp }}/kubectl"
        dest: "/usr/bin/kubectl"
        remote_src: true
        owner: root
        group: root
        mode: 0755

    - name: kubectl - Remove temporary directory
      ansible.builtin.file:
        path: "{{ kubectl_install_tmp }}"
        state: absent

    always:
    - name: kubectl - Confirm version
      tags: [init, update]
      ansible.builtin.command:
        cmd: kubectl version --client
      register: version
      changed_when: false

    - name: kubectl - Show version
      tags: [init, update]
      when: version is defined
      ansible.builtin.debug:
        msg: "Installed version: {{ version.stdout }}"

  # Helm
  - name: Helm
    tags: [init, update]
    block:

    - name: Helm - Create temporary directory
      ansible.builtin.file:
        path: "{{ helm_install_tmp }}"
        state: directory
        mode: 0700

    - name: Helm - Download install script
      ansible.builtin.uri:
        method: GET
        url: "{{ helm_install_url }}"
        dest: "{{ helm_install_tmp }}/get_helm.sh"
        follow_redirects: safe
        mode: 0700

    - name: Helm - Install
      ansible.builtin.command:
        cmd: /bin/bash -c {{ helm_install_tmp }}/get_helm.sh
      register: install_result
      changed_when: install_result.rc == 0

    - name: Helm - Remove temporary directory
      ansible.builtin.file:
        path: "{{ helm_install_tmp }}"
        state: absent

    always:
    - name: Helm - Confirm version
      tags: [init, update]
      ansible.builtin.command:
        cmd: helm version
      register: version
      changed_when: false

    - name: Helm - Show version
      tags: [init, update]
      when: version is defined
      ansible.builtin.debug:
        msg: "Installed version: {{ version.stdout }}"

  # Formulas
  - name: Formulas
    block:

    - name: Homebrew - List formulas
      tags: [init, update]
      ansible.builtin.debug:
        msg: "Formulas: {{ formulas }}"

    # brew install
    - name: Homebrew - Install formulas
      tags: init
      community.general.homebrew:
        name: "{{ formulas }}"
        state: present
        update_homebrew: true

    # brew upgrade
    - name: Homebrew - Upgrade formulas
      tags: update
      community.general.homebrew:
        name: "{{ formulas }}"
        state: latest
        update_homebrew: true
