- name: NVIDIA
  hosts: all
  gather_facts: false
  vars_files:
    - ../vars/main.yml

  tasks:
  # Repository - Container Toolkit
  - name: Repository - Container Toolkit
    tags: init
    block:

    - name: Create /etc/apt/keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: 0755

    # wget -O- https://nvidia.github.io/libnvidia-container/gpgkey | gpg --dearmor | sudo tee /etc/apt/keyrings/nvidia-container-toolkit-keyring.gpg > /dev/null
    - name: Download GPG apt key
      ansible.builtin.uri:
        method: GET
        url: https://nvidia.github.io/libnvidia-container/gpgkey
        dest: /tmp/nvidia-container-toolkit.gpg
        follow_redirects: safe
        mode: 0644

    - name: Import GPG key
      ansible.builtin.command:
        cmd: gpg --dearmor --output /etc/apt/keyrings/nvidia-container-toolkit-keyring.gpg --yes /tmp/nvidia-container-toolkit.gpg

    # echo "deb [signed-by=/etc/apt/keyrings/nvidia-container-toolkit-keyring.gpg] https://nvidia.github.io/libnvidia-container/stable/deb/$(dpkg --print-architecture) /" | sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list > /dev/null
    - name: Add apt repository
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/nvidia-container-toolkit-keyring.gpg] https://nvidia.github.io/libnvidia-container/stable/deb/{{ deb_architecture[ansible_architecture] }} /

    - name: Remove GPG temporary key
      ansible.builtin.file:
        path: /tmp/nvidia-container-toolkit.gpg
        state: absent

  # Repository - CUDA Toolkit
  - name: Repository - CUDA Toolkit
    tags: init
    block:

    - name: Download repository pin
      ansible.builtin.uri:
        method: GET
        url: https://developer.download.nvidia.com/compute/cuda/repos/wsl-ubuntu/x86_64/cuda-wsl-ubuntu.pin
        dest: /etc/apt/preferences.d/cuda-repository-pin-600
        follow_redirects: safe
        mode: 0644

    - name: Download and install repository deb package
      ansible.builtin.apt:
        deb: https://developer.download.nvidia.com/compute/cuda/12.8.1/local_installers/cuda-repo-wsl-ubuntu-12-8-local_12.8.1-1_amd64.deb
        state: present

    - name: Find keyring file
      ansible.builtin.find:
        paths: /var/cuda-repo-wsl-ubuntu-12-8-local
        patterns: "cuda-*-keyring.gpg"
      register: keyring_file

    - name: Copy keyring to /usr/share/keyrings/
      ansible.builtin.copy:
        src: "{{ keyring_file.files[0].path }}"
        dest: /usr/share/keyrings/
        remote_src: true
        mode: 0644
      when: keyring_file.files | length > 0

  # Packages
  - name: Packages
    block:

    # sudo apt update -y
    - name: Update cache
      tags: [init, update]
      ansible.builtin.apt:
        update_cache: true

    - name: List packages
      tags: [init, update]
      ansible.builtin.debug:
        msg: "packages: {{ nvidia_packages }}"

    # sudo apt install -y
    - name: Install packages
      tags: init
      ansible.builtin.apt:
        name: "{{ nvidia_packages }}"
        state: present

    # sudo apt upgrade -y
    - name: Upgrade packages
      tags: update
      ansible.builtin.apt:
        name: "{{ nvidia_packages }}"
        state: latest

  # Docker Configuration
  - name: Docker Configuration
    tag: init
    block:

    - name: Run toolkit runtime configuration
      ansible.builtin.command: nvidia-ctk runtime configure --runtime=docker

    - name: Restart Docker service
      ansible.builtin.systemd:
        name: docker
        state: restarted
        enabled: true
