- name: NVIDIA
  hosts: all
  gather_facts: true
  vars_files:
    - ../vars/main.yml

  tasks:
  # Repository - Container Toolkit
  # wget -O- https://nvidia.github.io/libnvidia-container/gpgkey | gpg --dearmor | sudo tee /etc/apt/keyrings/nvidia-container-toolkit-keyring.gpg > /dev/null
  # echo "deb [signed-by=/etc/apt/keyrings/nvidia-container-toolkit-keyring.gpg] https://nvidia.github.io/libnvidia-container/stable/deb/$(dpkg --print-architecture) /" | sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list > /dev/null
  - name: Repository
    tags: init
    ansible.builtin.include_tasks:
      file: ../tasks/repository.yml
    vars:
      key_url: https://nvidia.github.io/libnvidia-container/gpgkey
      key_output: /etc/apt/keyrings/nvidia-container-toolkit-keyring.gpg
      repository: "deb [signed-by=/etc/apt/keyrings/nvidia-container-toolkit-keyring.gpg] https://nvidia.github.io/libnvidia-container/stable/deb/{{ deb_architecture[ansible_architecture] }} /"

  # Repository - CUDA Toolkit
  - name: Repository - CUDA Toolkit
    become: true
    tags: init
    block:

    - name: Download repository pin
      ansible.builtin.uri:
        method: GET
        url: https://developer.download.nvidia.com/compute/cuda/repos/wsl-ubuntu/x86_64/cuda-wsl-ubuntu.pin
        dest: /etc/apt/preferences.d/cuda-repository-pin-600
        follow_redirects: safe
        mode: 0644

    - name: Download and install repository deb package
      ansible.builtin.apt:
        deb: https://developer.download.nvidia.com/compute/cuda/12.8.1/local_installers/cuda-repo-wsl-ubuntu-12-8-local_12.8.1-1_amd64.deb
        state: present

    - name: Find keyring file
      ansible.builtin.find:
        paths: /var/cuda-repo-wsl-ubuntu-12-8-local
        patterns: "cuda-*-keyring.gpg"
      register: keyring_file

    - name: Copy keyring to /usr/share/keyrings/
      ansible.builtin.copy:
        src: "{{ keyring_file.files[0].path }}"
        dest: /usr/share/keyrings/
        remote_src: true
        mode: 0644
      when: keyring_file.files | length > 0

  # Packages
  - name: Packages
    tags: [init, update]
    ansible.builtin.include_tasks:
      file: ../tasks/packages.yml
    vars:
      package_list: "{{ nvidia_packages }}"

  # Docker Configuration
  - name: Docker Configuration
    tags: init
    block:

    - name: Run toolkit runtime configuration
      ansible.builtin.command: nvidia-ctk runtime configure --runtime=docker

    - name: Restart Docker service
      ansible.builtin.systemd:
        name: docker
        state: restarted
        enabled: true
