#!/bin/zsh
# .zshrc

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
xterm-color | *-256color) color_prompt=yes ;;
esac

# ---------------------------------------------------------------------------- #
#               ------- History ------
# ---------------------------------------------------------------------------- #
setopt hist_ignore_all_dups
setopt hist_ignore_space
HISTSIZE=9999

# ---------------------------------------------------------------------------- #
#               ------- Environment ------
# ---------------------------------------------------------------------------- #

# fzf
export FZF_BASE=/home/linuxbrew/.linuxbrew/bin/fzf
export FZF_DEFAULT_COMMAND='fzf'

DISABLE_FZF_AUTO_COMPLETION="false"
DISABLE_FZF_KEY_BINDINGS="false"

# Zoxide
eval "$(zoxide init zsh --cmd cd)"

# ---------------------------------------------------------------------------- #
#               ------- Zsh ------
# ---------------------------------------------------------------------------- #

# Clear screen, keep buffer
clear-keep-buffer() {
  zle clear-screen
}
zle -N clear-keep-buffer

# Command line buffer editor
autoload -Uz edit-command-line
zle -N edit-command-line

# Copy current command to clipboard
copy-command() {
  print -rn -- "$BUFFER" | wl-copy
}
zle -N copy-command

# zsh move
autoload -Uz zmv

# ---------------------------------------------------------------------------- #
#               ------- Zsh - Key Bindings ------
# ---------------------------------------------------------------------------- #
bindkey '^zx' clear-keep-buffer
bindkey '^ze' edit-command-line
bindkey '^zc' copy-command

# Magic space
bindkey ' ' magic-space

# Hotkeys
bindkey -s '^zgc' 'git commit -m ""\C-b'
bindkey -s '^zgcv' 'git commit --no-verify -m ""\C-b'

# ---------------------------------------------------------------------------- #
#               ------- Alias-Finder ------
# ---------------------------------------------------------------------------- #
zstyle ':omz:plugins:alias-finder' autoload yes # disabled by default
zstyle ':omz:plugins:alias-finder' longer yes   # disabled by default
zstyle ':omz:plugins:alias-finder' exact yes    # disabled by default
zstyle ':omz:plugins:alias-finder' cheaper yes  # disabled by default

# ---------------------------------------------------------------------------- #
#               ------- Docker ------
# ---------------------------------------------------------------------------- #
zstyle ':completion:*:*:docker:*' option-stacking yes
zstyle ':completion:*:*:docker-*:*' option-stacking yes

# ---------------------------------------------------------------------------- #
#               ------- Eza ------
# ---------------------------------------------------------------------------- #
zstyle ':omz:plugins:eza' 'dirs-first' yes
zstyle ':omz:plugins:eza' 'git-status' yes
zstyle ':omz:plugins:eza' 'header' no
zstyle ':omz:plugins:eza' 'show-group' yes
zstyle ':omz:plugins:eza' 'icons' yes
zstyle ':omz:plugins:eza' 'size-prefix' si # binary,none
# zstyle ':omz:plugins:eza' 'time-style' $TIME_STYLE
zstyle ':omz:plugins:eza' 'hyperlink' no

# ---------------------------------------------------------------------------- #
#               ------- Antidote --------
# ---------------------------------------------------------------------------- #
source ${HOME}/.local/antidote/antidote.zsh
antidote load ${HOME}/.config/zsh/plugins.txt

# ---------------------------------------------------------------------------- #
#               ------- Personal Aliases & Functions --------
# ---------------------------------------------------------------------------- #
function source-if-exists() { if test -r "$1"; then source "$1"; fi; }

source-if-exists ~/.config/sh/functions.sh
source-if-exists ~/.config/sh/aliases.sh
source-if-exists ~/.kube/aliases.sh

function load-aliases-and-functions() {
  source ~/.config/sh/aliases.sh
  source ~/.config/sh/functions.sh
}

precmd_functions+=(load-aliases-and-functions)

# ---------------------------------------------------------------------------- #
#               ------- Completions --------
# ---------------------------------------------------------------------------- #
autoload -Uz bashcompinit
bashcompinit

# Infrastructure as Code (IaC)
eval "$(pulumi gen-completion zsh)"

# Language - Python
eval "$(register-python-argcomplete cz)"
eval "$(register-python-argcomplete pipx)"
eval "$(COMPLETE=zsh prek)"
source ${HOME}/.pyenv/completions/pyenv.zsh

# Orchestration
eval "$(grype completion zsh)"
eval "$(stern --completion zsh)"
eval "$(trivy completion zsh)"

# Version Control System (VCS)
eval "$(gitleaks completion zsh)"
eval "$(_GITLINT_COMPLETE=zsh_source gitlint)"

# Tools
eval "$(gonzo completion zsh)"
eval "$(just --completions zsh)"
eval "$(yq shell-completion zsh)"

# ---------------------------------------------------------------------------- #
#               ------- Oh My Posh --------
# ---------------------------------------------------------------------------- #
if [ "$TERM_PROGRAM" != "Apple_Terminal" ]; then
  eval "$(oh-my-posh init zsh --config ~/.config/oh-my-posh/default.toml)"
fi

# ---------------------------------------------------------------------------- #
#               ------- HHighlighter --------
# ---------------------------------------------------------------------------- #
hli() {
    _usage() {
        echo "usage: YOUR_COMMAND | h [-idn] args...
    -i : ignore case
    -d : disable regexp
    -n : invert colors"
    }

    local _OPTS

    # detect pipe or tty
    if [[ -t 0 ]]; then
        _usage
        return
    fi

    # manage flags
    while getopts ":idnQ" opt; do
        case $opt in
            i) _OPTS+=" -i " ;;
            d)  _OPTS+=" -Q " ;;
            n) n_flag=true ;;
            Q)  _OPTS+=" -Q " ;;
                # let's keep hidden compatibility with -Q for original ack users
            \?) _usage
                return ;;
        esac
    done

    shift $(($OPTIND - 1))

    # set zsh compatibility
    [[ -n $ZSH_VERSION ]] && setopt localoptions && setopt ksharrays && setopt ignorebraces

    local _i=0

    if [[ -n $H_COLORS_FG ]]; then
        local _CSV="$H_COLORS_FG"
        local OLD_IFS="$IFS"
        IFS=','
        local _COLORS_FG=()
        if [[ -n $ZSH_VERSION ]]; then
            _COLORS_FG=($=_CSV)
        else
            for entry in $_CSV; do
              _COLORS_FG=("${_COLORS_FG[@]}" "$entry")
            done
        fi
        IFS="$OLD_IFS"
    else
        _COLORS_FG=(
                "underline bold red" \
                "underline bold green" \
                "underline bold yellow" \
                "underline bold blue" \
                "underline bold magenta" \
                "underline bold cyan"
                )
    fi

    if [[ -n $H_COLORS_BG ]]; then
        local _CSV="$H_COLORS_BG"
        local OLD_IFS="$IFS"
        IFS=','
        local _COLORS_BG=()
        if [[ -n $ZSH_VERSION ]]; then
            _COLORS_BG=($=_CSV)
        else
            for entry in $_CSV; do
              _COLORS_BG=("${_COLORS_BG[@]}" "$entry")
            done
        fi
        IFS="$OLD_IFS"
    else
        _COLORS_BG=(
                "bold on_red" \
                "bold on_green" \
                "bold black on_yellow" \
                "bold on_blue" \
                "bold on_magenta" \
                "bold on_cyan" \
                "bold black on_white"
                )
    fi

    if [[ -z $n_flag ]]; then
        #inverted-colors-last scheme
        _COLORS=("${_COLORS_FG[@]}" "${_COLORS_BG[@]}")
    else
        #inverted-colors-first scheme
        _COLORS=("${_COLORS_BG[@]}" "${_COLORS_FG[@]}")
    fi

    if [[ "$#" -gt ${#_COLORS[@]} ]]; then
        echo "You have passed to hhighlighter more keywords to search than the number of configured colors.
Check the content of your H_COLORS_FG and H_COLORS_BG environment variables or unset them to use default 12 defined colors."
        return 1
    fi

    if [ -n "$ZSH_VERSION" ]; then
       local WHICH="whence"
    else [ -n "$BASH_VERSION" ]
       local WHICH="type -P"
    fi

    if ! ACKGREP_LOC="$($WHICH ack-grep)" || [ -z "$ACKGREP_LOC" ]; then
        if ! ACK_LOC="$($WHICH ack)" || [ -z "$ACK_LOC" ]; then
            echo "ERROR: Could not find the ack or ack-grep commands"
            return 1
        else
            local ACK=$($WHICH ack)
        fi
    else
        local ACK=$($WHICH ack-grep)
    fi

    # build the filtering command
    for keyword in "$@"
    do
        local _COMMAND=$_COMMAND"$ACK $_OPTS --noenv --flush --passthru --color --color-match=\"${_COLORS[$_i]}\" '$keyword' |"
        _i=$_i+1
    done
    #trim ending pipe
    _COMMAND=${_COMMAND%?}
    #echo "$_COMMAND"
    cat - | eval $_COMMAND
}
