#!/bin/zsh
# .zshenv

# User specific environment and startup programs
export USER=$(whoami)
export HOME=/home/${USER}

#==============================================================================#
#               ------- Environment ------                                     #
#==============================================================================#
export PATH=~/.local/bin:${PATH}

export EDITOR='code --wait'
export KUBE_EDITOR='code --wait'

# Bat
export BAT_THEME="Visual Studio Dark+"

# Go
export GOPATH=~/go
export PATH=/usr/local/go/bin:${GOPATH}/bin:${PATH}

# Homebrew
export PATH=/home/linuxbrew/.linuxbrew/bin:${PATH}
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# NodeJS
export PATH=${HOME}/node_modules/.bin:${PATH}

# Pulumi
export PATH=~/.pulumi/bin:${PATH}

# pyenv
export PYENV_ROOT=${HOME}/.pyenv
export PATH=${PYENV_ROOT}/bin:${PATH}
if command -v pyenv 1>/dev/null 2>&1; then
 eval "$(pyenv init -)"
fi
eval "$(pyenv virtualenv-init -)"
