#!/bin/zsh
# .zshrc

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
  xterm-color|*-256color) color_prompt=yes;;
esac

#==============================================================================#
#               ------- History ------                                         #
#==============================================================================#
setopt hist_ignore_all_dups
setopt hist_ignore_space
HISTSIZE=9999

#==============================================================================#
#               ------- Environment ------                                     #
#==============================================================================#

# fzf
export FZF_BASE=/usr/bin/fzf
export FZF_DEFAULT_COMMAND='fzf'

DISABLE_FZF_AUTO_COMPLETION="false"
DISABLE_FZF_KEY_BINDINGS="false"

# Zoxide
eval "$(zoxide init zsh --cmd cd)"

#==============================================================================#
#               ------- Antidote --------                                      #
#==============================================================================#
source ${HOME}/.local/antidote/antidote.zsh
antidote load ${HOME}/.config/zsh/plugins.txt

#==============================================================================#
#               ------- Alias-Finder ------                                    #
#==============================================================================#
zstyle ':omz:plugins:alias-finder' autoload yes # disabled by default
zstyle ':omz:plugins:alias-finder' longer yes # disabled by default
zstyle ':omz:plugins:alias-finder' exact yes # disabled by default
zstyle ':omz:plugins:alias-finder' cheaper yes # disabled by default

#==============================================================================#
#               ------- Docker ------                                          #
#==============================================================================#
zstyle ':completion:*:*:docker:*' option-stacking yes
zstyle ':completion:*:*:docker-*:*' option-stacking yes

#==============================================================================#
#               ------- Eza ------                                             #
#==============================================================================#
zstyle ':omz:plugins:eza' 'dirs-first' yes
zstyle ':omz:plugins:eza' 'git-status' yes
zstyle ':omz:plugins:eza' 'header' no
zstyle ':omz:plugins:eza' 'show-group' yes
zstyle ':omz:plugins:eza' 'icons' yes
zstyle ':omz:plugins:eza' 'size-prefix' si # binary,none
# zstyle ':omz:plugins:eza' 'time-style' $TIME_STYLE
zstyle ':omz:plugins:eza' 'hyperlink' no

#==============================================================================#
#               ------- Personal Aliases & Functions --------                  #
#==============================================================================#
function source_if_exists (){ if test -r "$1"; then source "$1"; fi; }

source_if_exists ~/.config/sh/aliases.sh
source_if_exists ~/.config/sh/functions.sh
source_if_exists ~/.kube/aliases.sh

precmd (){
  source ~/.config/sh/aliases.sh
  source ~/.config/sh/functions.sh
}

#==============================================================================#
#               ------- Oh My Posh --------                                    #
#==============================================================================#
if [ "$TERM_PROGRAM" != "Apple_Terminal" ]; then
  eval "$(oh-my-posh init zsh --config ~/.config/oh-my-posh/default.toml)"
fi

#==============================================================================#
#               ------- Completions --------                                   #
#==============================================================================#
eval "$(gitleaks completion zsh)"
