- name: Go
  hosts: all
  gather_facts: false
  vars_files:
    - ../vars/main.yml

  tasks:
  # -------------------------------------------------------------------------- #
  #               ------- Packages ------
  # -------------------------------------------------------------------------- #
  - name: Packages
    block:

    # wget -c https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz
    # sudo tar -C /usr/local/ -xzf go{{ go_version }}.linux-amd64.tar.gz
    - name: Install
      tags: [init, update]
      ansible.builtin.unarchive:
        src: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
        dest: "/usr/local"
        remote_src: true
        mode: 0755

    # # sudo apt update -y && sudo apt install -y golang-go
    # - name: Install
    #   tags: init
    #   ansible.builtin.apt:
    #     name: golang-go
    #     state: present
    #     update_cache: true

    # # sudo apt update -y && sudo apt upgrade -y golang-go
    # - name: Upgrade
    #   tags: update
    #   ansible.builtin.apt:
    #     name: golang-go
    #     state: latest
    #     update_cache: true

    # ------------------------------------------------------------------------ #
    #               ------- Version ------
    # ------------------------------------------------------------------------ #
    always:
    - name: Confirm version
      tags: [init, update]
      ansible.builtin.command:
        cmd: /usr/local/go/bin/go version
      register: version
      changed_when: false

    - name: Show version
      tags: [init, update]
      when: version is defined
      ansible.builtin.debug:
        msg: "Installed version: {{ version.stdout }}"
