- name: Go
  hosts: all
  gather_facts: false
  vars_files:
    - ../vars/main.yml

  tasks:
  # Packages
  # wget -c https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz
  # sudo tar -C /usr/local/ -xzf go{{ go_version }}.linux-amd64.tar.gz
  - name: Install packages
    become: true
    tags: [init, update]
    ansible.builtin.unarchive:
      src: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
      dest: "/usr/local"
      remote_src: true
      mode: 0755

  # Packages
  # - name: Packages
  #   tags: [init, update]
  #   ansible.builtin.include_tasks:
  #     file: ../tasks/packages.yml
  #   vars:
  #     package_list: "golang-go"

  # Version
  - name: Version
    tags: [init, update]
    ansible.builtin.include_tasks:
      file: ../tasks/version.yml
    vars:
      cmd: /usr/local/go/bin/go version
