- name: NodeJS
  hosts: all
  gather_facts: true
  vars_files:
    - ../vars/main.yml

  tasks:
  # Dependencies
  - name: Dependencies
    tags: [init, update]
    ansible.builtin.include_tasks:
      file: ../tasks/packages.yml
    vars:
      package_list: "{{ node_dependencies }}"
      package_type: "dependencies"

  # Repository
  - name: Repository
    tags: init
    ansible.builtin.include_tasks:
      file: ../tasks/repository.yml
    vars:
      key_url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
      key_output: /etc/apt/keyrings/nodesource.gpg
      repository: deb [arch={{ deb_architecture[ansible_architecture] }} signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ node_major }}.x nodistro main

  # Packages
  - name: Packages
    tags: [init, update]
    ansible.builtin.include_tasks:
      file: ../tasks/packages.yml
    vars:
      package_list: "{{ node_packages }}"

  # Version
  - name: Version
    tags: [init, update]
    ansible.builtin.include_tasks:
      file: ../tasks/version.yml
    vars:
      cmd: node --version

  # NPM Packages
  - name: NPM Packages
    block:

    - name: NPM - Show packages
      tags: [init, update]
      ansible.builtin.debug:
        msg: "NPM packages: {{ npm_packages }}"

    # sudo npm install
    - name: NPM - Install packages
      become: true
      tags: init
      community.general.npm:
        name: "{{ item }}"
        global: true
        state: present
      loop: "{{ npm_packages }}"

    # sudo npm update
    - name: NPM - Upgrade packages
      become: true
      tags: update
      community.general.npm:
        name: "{{ item }}"
        global: true
        state: latest
      loop: "{{ npm_packages }}"
