- name: NodeJS
  hosts: all
  gather_facts: false
  vars_files:
    - ../vars/main.yml

  tasks:
  # -------------------------------------------------------------------------- #
  #               ------- Dependencies ------
  # -------------------------------------------------------------------------- #
  - name: Dependencies
    block:

    - name: Show dependencies
      tags: [init, update]
      ansible.builtin.debug:
        msg: "Dependencies: {{ node_dependencies }}"

    # sudo apt update -y && sudo apt install -y
    - name: Install dependencies
      tags: init
      ansible.builtin.apt:
        name: "{{ node_dependencies }}"
        state: present
        update_cache: true

    # sudo apt update -y && sudo apt upgrade -y
    - name: Upgrade dependencies
      tags: update
      ansible.builtin.apt:
        name: "{{ node_dependencies }}"
        state: latest
        update_cache: true

  # -------------------------------------------------------------------------- #
  #               ------- Repository ------
  # -------------------------------------------------------------------------- #
  - name: Repository
    tags: init
    block:

    - name: Create /etc/apt/keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: 0755

    # curl https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor --output /etc/apt/keyrings/nodesource.gpg
    - name: Download GPG apt key
      ansible.builtin.uri:
        method: GET
        url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
        dest: /tmp/nodejs.gpg
        follow_redirects: safe
        mode: 0644

    - name: Import GPG key
      ansible.builtin.command:
        cmd: gpg --dearmor --output /etc/apt/keyrings/nodesource.gpg --yes /tmp/nodejs.gpg

    # echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ node_major }}.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list > /dev/null
    - name: Add apt repository
      ansible.builtin.apt_repository:
        repo: deb [arch={{ deb_architecture[ansible_architecture] }} signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ node_major }}.x nodistro main

    - name: Remove temporary GPG key
      ansible.builtin.file:
        path: /tmp/nodejs.gpg
        state: absent

  # -------------------------------------------------------------------------- #
  #               ------- Packages ------
  # -------------------------------------------------------------------------- #
  - name: Packages
    block:

    - name: Show packages
      tags: [init, update]
      ansible.builtin.debug:
        msg: "Packages: {{ node_packages }}"

    # sudo apt update -y && sudo apt install -y
    - name: Install packages
      tags: init
      ansible.builtin.apt:
        name: "{{ node_packages }}"
        state: present
        update_cache: true

    # sudo apt update -y && sudo apt upgrade -y
    - name: Upgrade packages
      tags: update
      ansible.builtin.apt:
        name: "{{ node_packages }}"
        state: latest
        update_cache: true

  # -------------------------------------------------------------------------- #
  #               ------- Version ------
  # -------------------------------------------------------------------------- #
  - name: Version
    tags: [init, update]
    block:

    - name: Confirm version
      ansible.builtin.command:
        cmd: node --version
      register: version
      changed_when: false

    - name: Show version
      when: version is defined
      ansible.builtin.debug:
        msg: "Installed version: {{ version.stdout }}"

  # -------------------------------------------------------------------------- #
  #               ------- NPM Packages ------
  # -------------------------------------------------------------------------- #
  - name: NPM Packages
    block:

    - name: NPM - Show packages
      tags: [init, update]
      ansible.builtin.debug:
        msg: "NPM packages: {{ npm_packages }}"

    # sudo npm install
    - name: NPM - Install packages
      tags: init
      community.general.npm:
        name: "{{ npm_packages | join(' ') }}"
        global: true
        state: present

    # sudo npm update
    - name: NPM - Upgrade packages
      tags: update
      community.general.npm:
        name: "{{ npm_packages | join(' ') }}"
        global: true
        state: latest
