- name: Python
  hosts: all
  gather_facts: true
  vars_files:
    - ../vars/main.yml

  tasks:
  # -------------------------------------------------------------------------- #
  #               ------- Dependencies ------
  # -------------------------------------------------------------------------- #
  - name: Dependencies
    ansible.builtin.import_tasks:
      file: ../tasks/packages.yml
    vars:
      package_list: "{{ python_dependencies }}"
      package_type: "dependencies"

  # -------------------------------------------------------------------------- #
  #               ------- Packages ------
  # -------------------------------------------------------------------------- #
  - name: Packages
    ansible.builtin.import_tasks:
      file: ../tasks/packages.yml
    vars:
      package_list: "{{ python_packages }}"

  # -------------------------------------------------------------------------- #
  #               ------- PyPI ------
  # -------------------------------------------------------------------------- #
  - name: PyPI - Show packages
    tags: [init, update]
    ansible.builtin.debug:
      msg: "PyPI packages: {{ pip_packages }}"

  - name: PyPI Packages
    become: true
    block:
    # pip install
    - name: PyPI - Install packages
      tags: init
      ansible.builtin.pip:
        # extra_args: "--break-system-packages"
        name: "{{ pip_packages }}"
        state: present

    # pip install --upgrade
    - name: PyPI - Upgrade packages
      tags: update
      ansible.builtin.pip:
        # extra_args: "--break-system-packages"
        name: "{{ pip_packages }}"
        state: latest

    # pip install paramiko>3.5.1
    - name: PyPI - Install paramiko with minimum version
      tags: init
      ansible.builtin.pip:
        # extra_args: "--break-system-packages"
        name: paramiko>3.5.1
        state: present

  # -------------------------------------------------------------------------- #
  #               ------- PyPI - Force Reinstall ------
  # -------------------------------------------------------------------------- #
  - name: PyPI - Show packages to reinstall
    tags: [init, update]
    ansible.builtin.debug:
      msg: "PyPI packages to reinstall: {{ pip_force_reinstall_packages }}"

  - name: PyPI Reinstall Packages
    become: true
    block:

    # pip install --force-reinstall
    - name: PyPI - Force reinstall packages
      tags: init
      ansible.builtin.pip:
        # extra_args: "--break-system-packages"
        name: "{{ pip_force_reinstall_packages }}"
        state: forcereinstall

  # -------------------------------------------------------------------------- #
  #               ------- pyenv ------
  # -------------------------------------------------------------------------- #

  # Dependencies
  - name: pyenv - Dependencies
    ansible.builtin.import_tasks:
      file: ../tasks/packages.yml
    vars:
      package_list: "{{ pyenv_dependencies }}"
      package_type: "dependencies"

  # Installation
  # curl https://pyenv.run | bash
  - name: pyenv - Installation
    tags: init
    ansible.builtin.import_tasks:
      file: ../tasks/script.yml
    vars:
      url: "{{ pyenv_install_url }}"
      cmd: /tmp/install.sh

  # Upgrade
  - name: pyenv - Upgrade
    tags: update
    ansible.builtin.command:
      cmd: pyenv update
    register: upgrade_result
    changed_when: upgrade_result.rc == 0

  # Install Python
  - name: pyenv - Install Python
    tags: init
    ansible.builtin.shell:
      cmd: pyenv install {{ pyenv_python_version }}
      executable: "{{ ansible_user_shell }}"

  # -------------------------------------------------------------------------- #
  #               ------- pipx ------
  # -------------------------------------------------------------------------- #

  # Installation
  - name: pipx
    ansible.builtin.import_tasks:
      file: ../tasks/packages.yml
    vars:
      package_list: "pipx"

  # Version
  - name: pipx - Version
    tags: [init, update]
    ansible.builtin.import_tasks:
      file: ../tasks/version.yml
    vars:
      cmd: pipx --version

  # -------------------------------------------------------------------------- #
  #               ------- Pipx - Packages ------
  # -------------------------------------------------------------------------- #
  - name: Pipx - Show packages
    tags: [init, update]
    ansible.builtin.debug:
      msg: "Pipx packages: {{ pipx_packages }}"

  - name: Pipx Packages
    block:
    # pipx install
    - name: Pipx - Install packages
      tags: init
      community.general.pipx:
        name: "{{ item }}"
        state: present
      loop: "{{ pipx_packages }}"

    # pipx install --upgrade
    - name: Pipx - Upgrade packages
      tags: update
      community.general.pipx:
        name: "{{ item }}"
        state: latest
      loop: "{{ pipx_packages }}"

  # -------------------------------------------------------------------------- #
  #               ------- poetry ------
  # -------------------------------------------------------------------------- #
  - name: poetry - Version
    tags: [init, update]
    ansible.builtin.import_tasks:
      file: ../tasks/version.yml
    vars:
      cmd: ~/.local/bin/poetry --version

  # -------------------------------------------------------------------------- #
  #               ------- uv ------
  # -------------------------------------------------------------------------- #

  # Installation
  # curl -fsSL https://astral.sh/uv/install.sh | sh
  - name: uv - Installation
    tags: init
    ansible.builtin.import_tasks:
      file: ../tasks/script.yml
    vars:
      url: "{{ uv_install_url }}"
      cmd: /bin/sh -c /tmp/install.sh

  # Upgrade
  - name: uv - Upgrade
    tags: update
    ansible.builtin.command:
      cmd: uv self update
    register: upgrade_result
    changed_when: upgrade_result.rc == 0

  # Version
  - name: uv - Version
    tags: [init, update]
    ansible.builtin.import_tasks:
      file: ../tasks/version.yml
    vars:
      cmd: uv --version
