- name: Python
  hosts: all
  gather_facts: false
  vars:
    install_tmp: /tmp/pyenv
    install_url: https://pyenv.run
    packages:
      - python3
      - python3-docker # used by Ansible modules
      - python3-pip
      - python3-venv
      - python3.11-dev
      - python3.11-venv
      - python-is-python3
    pip_packages:
      - aiohttp
      - asyncer
      - filetype
      - gradio
      - markitdown
      - onnxruntime
      - pillow
      - Pygments
      - rembg
      - watchdog
    pyenv_dependencies:
      - build-essential
      - bzip2
      - libffi-dev
      - libncursesw5-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - zlib1g-dev
    pyenv_formulas:
      - pyenv
      - pyenv-virtualenv
  vars_files:
    - ../vars/main.yml

  tasks:
  # Packages
  - name: Packages
    block:

    - name: List packages
      tags: [init, update]
      ansible.builtin.debug:
        msg: "packages: {{ packages }}"

    # sudo apt update -y && sudo apt install -y
    - name: Install
      tags: init
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true

    # sudo apt update -y && sudo apt upgrade -y
    - name: Upgrade
      tags: update
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: latest
        update_cache: true

  # PyPI Packages
  - name: PyPI Packages
    block:

    - name: List packages
      tags: [init, update]
      ansible.builtin.debug:
        msg: "PyPI packages: {{ pip_packages }}"

    # pip install
    - name: PyPI - Install packages
      tags: init
      ansible.builtin.pip:
        name: "{{ pip_packages }}"
        state: present

    - name: PyPI - Install paramiko with minimum version
      tags: init
      ansible.builtin.pip:
        name: paramiko>3.5.1
        state: present

    # pip install --upgrade
    - name: PyPI - Upgrade packages
      tags: update
      ansible.builtin.pip:
        name: "{{ pip_packages }}"
        state: latest


  # Pyenv - Dependencies
  - name: Pyenv - Dependencies
    block:

    - name: pyenv - List dependencies
      tags: [init, update]
      ansible.builtin.debug:
        msg: "dependencies: {{ pyenv_dependencies }}"

    # sudo apt update -y && sudo apt install -y
    - name: pyenv - Install dependencies
      tags: init
      ansible.builtin.apt:
        name: "{{ pyenv_dependencies }}"
        state: present
        update_cache: true

    # sudo apt update -y && sudo apt upgrade -y
    - name: pyenv - Upgrade dependencies
      tags: update
      ansible.builtin.apt:
        name: "{{ pyenv_dependencies }}"
        state: latest
        update_cache: true

  # Pyenv
  - name: Pyenv
    become_user: ubuntu
    tags: [init, update]
    block:

    - name: Create temporary directory
      ansible.builtin.file:
        path: "{{ install_tmp }}"
        state: directory
        mode: 0700

    # curl https://pyenv.run | bash
    - name: Download install script
      ansible.builtin.uri:
        method: GET
        url: "{{ install_url }}"
        dest: "{{ install_tmp }}/pyenv.run"
        follow_redirects: safe
        mode: 0700

    - name: Install
      ansible.builtin.shell:
        cmd: "{{ install_tmp }}/pyenv.run"
        executable: /usr/bin/zsh
      register: install_result
      changed_when: install_result.rc == 0

    - name: Remove temporary directory
      ansible.builtin.file:
        path: "{{ install_tmp }}"
        state: absent

  # Pyenv - Default Python version
  - name: Pyenv - Default Python version
    become_user: ubuntu
    tags: init
    block:

    # pyenv install
    - name: pyenv - Install Python
      ansible.builtin.shell:
        cmd: pyenv install {{ python_version }}
        executable: /usr/bin/zsh

  # Pipx
  - name: Pipx
    block:

    # sudo apt update -y && sudo apt install -y pipx
    - name: pipx - Install
      tags: init
      ansible.builtin.apt:
        name: pipx
        state: present
        update_cache: true

    # sudo apt update -y && sudo apt upgrade -y pipx
    - name: pipx - Upgrade
      tags: update
      ansible.builtin.apt:
        name: pipx
        state: latest
        update_cache: true

    always:
    - name: pipx - Confirm version
      tags: [init, update]
      ansible.builtin.command:
        cmd: pipx --version
      register: version
      changed_when: false

    - name: pipx - Show version
      tags: [init, update]
      when: version is defined
      ansible.builtin.debug:
        msg: "Installed version: {{ version.stdout }}"

  # Commitizen
  - name: commitizen
    become_user: ubuntu
    block:

    # pipx install commitizen
    - name: Commitizen - Install
      tags: init
      community.general.pipx:
        name: commitizen
        state: present

    # pipx upgrade commitizen
    - name: Commitizen - Upgrade
      tags: update
      community.general.pipx:
        name: commitizen
        state: latest

    always:
    - name: Commitizen - Confirm version
      tags: [init, update]
      ansible.builtin.command:
        cmd: ~/.local/bin/cz version
      register: version
      changed_when: false

    - name: Commitizen - Show version
      tags: [init, update]
      when: version is defined
      ansible.builtin.debug:
        msg: "Installed version: {{ version.stdout }}"

  # Poetry
  - name: Poetry
    become_user: ubuntu
    block:

    # pipx install poetry
    - name: Poetry - Install
      tags: init
      community.general.pipx:
        name: poetry
        state: present

    # pipx upgrade poetry
    - name: Poetry - Upgrade
      tags: update
      community.general.pipx:
        name: poetry
        state: latest

    always:
    - name: Poetry - Confirm version
      tags: [init, update]
      ansible.builtin.command:
        cmd: ~/.local/bin/poetry --version
      register: version
      changed_when: false

    - name: Poetry - Show version
      tags: [init, update]
      when: version is defined
      ansible.builtin.debug:
        msg: "Installed version: {{ version.stdout }}"
