- name: WezTerm
  hosts: all
  gather_facts: true
  vars_files:
    - ../vars/main.yml

  tasks:
  # Repository
  # echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *" | sudo tee /etc/apt/sources.list.d/wezterm.list > /dev/null
  - name: Repository
    tags: init
    ansible.builtin.include_tasks:
      file: ../tasks/repository.yml
    vars:
      key_url: https://apt.fury.io/wez/gpg.key
      key_output: /etc/apt/keyrings/wezterm-fury.gpg
      repository: "deb [arch={{ deb_architecture[ansible_architecture] }} signed-by=/etc/apt/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *"

  # Packages
  - name: Packages
    tags: [init, update]
    ansible.builtin.include_tasks:
      file: ../tasks/packages.yml
    vars:
      package_list: "{{ wezterm_packages }}"
