- name: Package Manager
  tags: [ init, update ]
  become: true
  vars:
    ubuntu:
      - build-essential
      - curl
      - git
      - vim # text editor of choice
      - zip

  block:
  # apt update -y
  - name: Package Manager - Update cache
    apt:
      update_cache: true

  - name: Package Manager - List of packages
    debug:
      msg: "packages: {{ ubuntu }}"

  # apt install -y
  - name: Package Manager - Install/update packages
    apt:
      name: "{{ ubuntu }}"
      state: latest

  # apt remove -y
  # - name: Package Manager - Remove packages
  #   apt:
  #     name:
  #       -
  #     state: absent

  # apt autoclean
  - name: Package Manager - Cleans the local repository of package files that can no longer be downloaded
    apt:
      autoclean: true

  # apt autoremove
  - name: Package Manager - Remove unused dependencies
    apt:
      autoremove: true
