- name: Manage packages
  tags: [ init, update ]
  become: true
  block:
  # apt update -y
  - name: Update cache
    apt:
      update_cache: true

  # apt install -y
  - name: Install/update packages
    apt:
      package:
        name: "{{ item }}"
        state: latest
      loop: "{{ packages }}"
      vars:
        packages:
          - build-essential
          - curl
          - git
          - vim
          - zip

  # apt remove -y
  # - name: Remove packages
  #   apt:
  #     pkg:
  #       -
  #     state: absent

  # apt autoclean
  - name: Cleans the local repository of retrieved package files that can no longer be downloaded
    apt:
      autoclean: true

  # apt autoremove
  - name: Remove unused dependency packages
    apt:
      autoremove: true
