- name: Package Manager
  hosts: all
  gather_facts: false
  vars:
    packages:
      - build-essential
      - curl
      - git
      - htop # resources monitoring
      - net-tools
      - pwgen # random password generator
      - software-properties-common
      - tzdata # timezone
      - vim # text editor of choice
      - zip

  tasks:
  # apt
  - name: apt
    block:

    # apt update -y
    - name: Update cache
      tags: [init, update]
      ansible.builtin.apt:
        update_cache: true

    - name: List packages
      tags: [init, update]
      debug:
        msg: "packages: {{ packages }}"

    - name: Initialization
      tags: init
      block:

      # apt install -y
      - name: Install packages
        ansible.builtin.apt:
          name: "{{ packages }}"
          state: present

      # apt remove -y
      # - name: Remove packages
      #   ansible.builtin.apt:
      #     name:
      #       -
      #     state: absent

    # apt upgrade -y
    - name: Upgrade packages
      tags: update
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: latest

    - name: Cleaning
      tags: clean
      block:

      # apt autoclean
      - name: Cleans the local repository of package files that can no longer be downloaded
        ansible.builtin.apt:
          autoclean: true

      # apt autoremove
      - name: Remove unused dependencies
        ansible.builtin.apt:
          autoremove: true
