- name: Package Manager
  become: true
  hosts: all
  vars:
    ubuntu:
      - build-essential
      - curl
      - git
      - vim # text editor of choice
      - zip

  tasks:
  # apt update -y
  - name: Package Manager - Update cache
    tags: [init, update]
    apt:
      update_cache: true

  - name: Package Manager - List of packages
    tags: [init, update]
    debug:
      msg: "packages: {{ ubuntu }}"

  - name: Package Manager - Initialization
    tags: init
    block:

    # apt install -y
    - name: Package Manager - Install packages
      apt:
        name: "{{ ubuntu }}"
        state: present

    # apt remove -y
    # - name: Package Manager - Remove packages
    #   apt:
    #     name:
    #       -
    #     state: absent

  - name: Package Manager - Upgrade
    tags: update
    block:

    # apt upgrade -y
    - name: Package Manager - Upgrade packages
      apt:
        name: "{{ ubuntu }}"
        state: latest

  - name: Package Manager - Cleaning
    tags: clean
    block:

    # apt autoclean
    - name: Package Manager - Cleans the local repository of package files that can no longer be downloaded
      apt:
        autoclean: true

    # apt autoremove
    - name: Package Manager - Remove unused dependencies
      apt:
        autoremove: true
