- name: Package Manager
  hosts: all
  gather_facts: false
  become: true
  vars:
    ubuntu:
      - build-essential
      - curl
      - git
      - vim # text editor of choice
      - zip

  tasks:
  # apt update -y
  - name: Update cache
    tags: [init, update]
    ansible.builtin.apt:
      update_cache: true

  - name: List packages
    tags: [init, update]
    debug:
      msg: "packages: {{ ubuntu }}"

  - name: Initialization
    tags: init
    block:

    # apt install -y
    - name: Install packages
      ansible.builtin.apt:
        name: "{{ ubuntu }}"
        state: present

    # apt remove -y
    # - name: Remove packages
    #   ansible.builtin.apt:
    #     name:
    #       -
    #     state: absent

  # apt upgrade -y
  - name: Upgrade packages
    tags: update
    ansible.builtin.apt:
      name: "{{ ubuntu }}"
      state: latest

  - name: Cleaning
    tags: clean
    block:

    # apt autoclean
    - name: Cleans the local repository of package files that can no longer be downloaded
      ansible.builtin.apt:
        autoclean: true

    # apt autoremove
    - name: Remove unused dependencies
      ansible.builtin.apt:
        autoremove: true
