- name: Python
  hosts: all
  gather_facts: false
  vars:
    dependencies_pyenv:
      - libncursesw5-dev
      - libreadline-dev
      - libsqlite3-dev
      - zlib1g-dev
    packages:
      - python3
      - python3-pip

  tasks:
  # Python
  - name: Python
    block:

    - name: List packages
      tags: [init, update]
      debug:
        msg: "packages: {{ packages }}"

    - name: Install
      tags: init
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true

    - name: Upgrade
      tags: update
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: latest
        update_cache: true

  # pyenv
  - name: pyenv
    block:

    - name: pyenv - List dependencies
      tags: [init, update]
      debug:
        msg: "dependencies: {{ dependencies_pyenv }}"

    - name: pyenv - Install dependencies
      tags: init
      ansible.builtin.apt:
        name: "{{ dependencies_pyenv }}"
        state: present
        update_cache: true

    - name: pyenv - Upgrade dependencies
      tags: update
      ansible.builtin.apt:
        name: "{{ dependencies_pyenv }}"
        state: latest
        update_cache: true

    - name: pyenv - Install
      tags: init
      community.general.homebrew:
        name:
          - pyenv
          - pyenv-virtualenv
        state: present
        update_homebrew: true

    - name: pyenv - Upgrade
      tags: update
      community.general.homebrew:
        name:
          - pyenv
          - pyenv-virtualenv
        state: latest
        update_homebrew: true

  # pipx
  - name: pipx
    block:

    - name: pipx - Install
      tags: init
      ansible.builtin.apt:
        name: pipx
        state: present
        update_cache: true

    - name: pipx - Upgrade
      tags: update
      ansible.builtin.apt:
        name: pipx
        state: latest
        update_cache: true

  # poetry
  - name: poetry
    block:

    - name: poetry - Install
      tags: init
      community.general.pipx:
        name: poetry
        state: present

    - name: poetry - Upgrade
      tags: update
      community.general.pipx:
        name: poetry
        state: latest
