- name: Python
  hosts: all
  gather_facts: false
  become: true
  vars:
    packages:
      - python3
      - python3-pip

  tasks:
  # Python
  - name: List packages
    tags: [init, update]
    debug:
      msg: "packages: {{ packages }}"

  - name: Install
    tags: init
    ansible.builtin.apt:
      name: "{{ packages }}"
      state: present
      update_cache: true

  - name: Upgrade
    tags: update
    ansible.builtin.apt:
      name: "{{ packages }}"
      state: latest
      update_cache: true

  # pipx
  - name: Install pipx
    tags: init
    ansible.builtin.apt:
      name: pipx
      state: present
      update_cache: true

  - name: Upgrade pipx
    tags: update
    ansible.builtin.apt:
      name: pipx
      state: latest
      update_cache: true

  # poetry
  - name: Install poetry
    tags: init
    community.general.pipx:
      name: poetry
      state: present

  - name: Upgrade poetry
    tags: update
    community.general.pipx:
      name: poetry
      state: latest
