- name: Zoxide
  hosts: all
  gather_facts: false
  vars:
    install_tmp: /tmp/zoxide
    install_url: https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh

  tasks:
  # Zoxide
  - name: Zoxide
    become_user: ubuntu
    tags: [init, update]
    block:

    - name: Create temporary directory
      ansible.builtin.file:
        path: "{{ install_tmp }}"
        state: directory
        mode: 0700

    - name: Download install script
      ansible.builtin.get_url:
        url: "{{ install_url }}"
        dest: "{{ install_tmp }}/install.sh"
        mode: 0700

    - name: Install
      ansible.builtin.command:
        cmd: /bin/sh -c {{ install_tmp }}/install.sh
      register: install_result
      changed_when: install_result.rc == 0

    - name: Remove temporary directory
      ansible.builtin.file:
        path: "{{ install_tmp }}"
        state: absent

    always:
    - name: Confirm version
      ansible.builtin.command:
        cmd: zoxide --version
      register: version
      changed_when: false

    - name: Show version
      when: version is defined
      ansible.builtin.debug:
        msg: "Installed version: {{ version.stdout }}"
