- name: Run APT
  tags: [ init, update ]
  become: true
  block:
  - name: Update cache
    apt:
      update_cache: true

  # apt list --installed
  - name: Install/update packages
    apt:
      pkg:
        - build-essential
        - curl
        - firefox # Browser of choice
        - git
        - gnupg
        - htop
        - lsb-release
        - net-tools
        - openssl
        - pwgen # Easily generate random password
        - python3
        - python3-docker
        - python3-passlib # libraries used by Ansible modules
        - python3-pip
        - software-properties-common
        - vim
        - xdg-utils # Enable starting a browser to run aws sso login
        - zip
        - zsh
      state: latest

  # - name: Remove packages
  #   become: true
  #   apt:
  #     pkg:
  #       -
  #     state: absent

  - name: Remove useless packages from the cache
    apt:
      autoclean: true

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: true
