# https://cloud.google.com/sdk/docs/install
- name: GCP
  hosts: all
  gather_facts: true
  vars:
    dependencies:
      - apt-transport-https
      - ca-certificates
      - curl
      - firefox
      - gnupg
      - xdg-utils # Enable starting a browser to run gcloud init
    packages:
      - google-cloud-cli
      - google-cloud-cli-gke-gcloud-auth-plugin
  vars_files:
    - ../vars/main.yml

  tasks:
  # Dependencies
  - name: Dependencies
    block:

    - name: List dependencies
      tags: [init, update]
      ansible.builtin.debug:
        msg: "dependencies: {{ dependencies }}"

    # sudo apt update -y && sudo apt install -y
    - name: Install dependencies
      tags: init
      ansible.builtin.apt:
        name: "{{ dependencies }}"
        state: present
        update_cache: true

    # sudo apt update -y && sudo apt upgrade -y
    - name: Upgrade dependencies
      tags: update
      ansible.builtin.apt:
        name: "{{ dependencies }}"
        state: latest
        update_cache: true

  # Repository
  - name: Repository
    tags: init
    block:

    - name: Create /etc/apt/keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: 0755

    # curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
    - name: Download GPG apt key
      ansible.builtin.uri:
        method: GET
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        dest: /tmp/gcp.gpg
        follow_redirects: safe
        mode: 0644

    - name: Import GPG key
      ansible.builtin.command:
        cmd: gpg --dearmor --output /etc/apt/keyrings/cloud.google.gpg --yes /tmp/gcp.gpg

    # echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list > /dev/null
    - name: Add apt repository
      ansible.builtin.apt_repository:
        repo: deb [arch={{ deb_architecture[ansible_architecture] }} signed-by=/etc/apt/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main

    - name: Remove GPG temporary key
      ansible.builtin.file:
        path: /tmp/gcp.gpg
        state: absent

  # Packages
  - name: Packages
    block:

    - name: List packages
      tags: [init, update]
      ansible.builtin.debug:
        msg: "packages: {{ packages }}"

    # sudo apt update -y && sudo apt install -y
    - name: Install
      tags: init
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true

    # sudo apt update -y && sudo apt upgrade -y
    - name: Upgrade
      tags: update
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: latest
        update_cache: true

  # Version
  - name: Version
    tags: [init, update]
    block:

    - name: Confirm version
      ansible.builtin.command:
        cmd: gcloud --version
      register: version
      changed_when: false

    - name: Show version
      when: version is defined
      ansible.builtin.debug:
        msg: "Installed version: {{ version.stdout }}"
