# https://cloud.google.com/sdk/docs/install
- name: GCP
  hosts: all
  gather_facts: true
  vars_files:
    - ../vars/main.yml

  tasks:
  # -------------------------------------------------------------------------- #
  #               ------- Dependencies ------
  # -------------------------------------------------------------------------- #
  - name: Dependencies
    tags: [init, update]
    ansible.builtin.include_tasks:
      file: ../tasks/packages.yml
    vars:
      package_list: "{{ gcp_dependencies }}"
      package_type: "dependencies"

  # -------------------------------------------------------------------------- #
  #               ------- Repository ------
  # -------------------------------------------------------------------------- #
  - name: Repository
    tags: init
    block:

    - name: Create /etc/apt/keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: 0755

    # curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor --output /usr/share/keyrings/cloud.google.gpg
    - name: Download GPG apt key
      ansible.builtin.uri:
        method: GET
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        dest: /tmp/gcp.gpg
        follow_redirects: safe
        mode: 0644

    - name: Import GPG key
      ansible.builtin.command:
        cmd: gpg --dearmor --output /etc/apt/keyrings/cloud.google.gpg --yes /tmp/gcp.gpg

    # echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list > /dev/null
    - name: Add apt repository
      ansible.builtin.apt_repository:
        repo: deb [arch={{ deb_architecture[ansible_architecture] }} signed-by=/etc/apt/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main

    - name: Remove temporary GPG key
      ansible.builtin.file:
        path: /tmp/gcp.gpg
        state: absent

  # -------------------------------------------------------------------------- #
  #               ------- Packages ------
  # -------------------------------------------------------------------------- #
  - name: Packages
    tags: [init, update]
    ansible.builtin.include_tasks:
      file: ../tasks/packages.yml
    vars:
      package_list: "{{ gcp_packages }}"

  # -------------------------------------------------------------------------- #
  #               ------- Version ------
  # -------------------------------------------------------------------------- #
  - name: Version
    tags: [init, update]
    block:

    - name: Confirm version
      ansible.builtin.command:
        cmd: gcloud --version
      register: version
      changed_when: false

    - name: Show version
      when: version is defined
      ansible.builtin.debug:
        msg: "Installed version: {{ version.stdout }}"
