console_title_template = "{{ .Shell }} in {{ .Folder }}"
version = 3
final_space = true

[palette]
  black = "#262B44"
  blue = "#5d94e9"
  blue_docker = "#338bb8"
  blue_kube = "#4c70e6"
  green = "#6ac9a4"
  orange = "#e7772c"
  red = "#D81E5B"
  white = "#E0DEF4"
  yellow = "#ecaf3a"

[secondary_prompt]
  template = "<p:yellow,transparent></><,p:yellow> > </><p:yellow,transparent></> "
  foreground = "p:black"
  background = "transparent"

[transient_prompt]
  template = "<p:yellow,transparent></><,p:yellow> {{ .Folder }} </><p:yellow,transparent></> "
  foreground = "p:black"
  background = "transparent"

[[blocks]]
  type = "prompt"
  alignment = "left"

  [[blocks.segments]]
    leading_diamond = ""
    trailing_diamond = ""
    template = " {{ if .SSHSession }} {{ end }}{{ .UserName }} "
    foreground = "p:black"
    background = "p:yellow"
    type = "session"
    style = "diamond"

  [[blocks.segments]]
    template = "  {{ path .Path .Location }} "
    foreground = "p:white"
    powerline_symbol = ""
    background = "p:orange"
    type = "path"
    style = "powerline"

    [blocks.segments.properties]
      style = "folder"

  [[blocks.segments]]
    template = " {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} "
    foreground = "p:black"
    powerline_symbol = ""
    background = "p:green"
    type = "git"
    style = "powerline"
    foreground_templates = ["{{ if or (.Working.Changed) (.Staging.Changed) }}p:black{{ end }}", "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:white{{ end }}", "{{ if gt .Ahead 0 }}p:white{{ end }}"]
    background_templates = ["{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}", "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}", "{{ if gt .Ahead 0 }}#49416D{{ end }}", "{{ if gt .Behind 0 }}#7A306C{{ end }}"]

    [blocks.segments.properties]
      branch_max_length = 25
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    template = "  "
    foreground = "p:white"
    powerline_symbol = ""
    background = "p:yellow"
    type = "root"
    style = "powerline"

  [[blocks.segments]]
    leading_diamond = "<transparent,background></>"
    trailing_diamond = ""
    template = " {{ if gt .Code 0 }}{{ else }}{{ end }} "
    foreground = "p:white"
    background = "p:blue"
    type = "status"
    style = "diamond"
    background_templates = ["{{ if gt .Code 0 }}p:red{{ end }}"]

    [blocks.segments.properties]
      always_enabled = true

#==============================================================================#
#               ------- Right --------                                         #
#==============================================================================#
[[blocks]]
  type = "rprompt"

  # Languages
  [[blocks.segments]]
    type = "go"
    style = "plain"
    foreground = "p:blue_go"
    background = "transparent"
    template = " "

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    type = "python"
    style = "plain"
    foreground = "p:yellow_python"
    background = "transparent"
    template = " {{ if .Venv }}{{ .Venv }} "

    [blocks.segments.properties]
      display_default	= true
      display_mode = "files"
      fetch_version = false
      fetch_virtual_env = true

  [[blocks.segments]]
    template = "in <p:blue><b>{{ .Name }}</b></> "
    foreground = "p:white"
    background = "transparent"
    type = "shell"
    style = "plain"

  [[blocks.segments]]
    template = "at <p:blue><b>{{ .CurrentDate | date "15:04:05" }}</b></>"
    foreground = "p:white"
    background = "transparent"
    type = "time"
    style = "plain"

#==============================================================================#
#               ------- Tooltips --------                                      #
#==============================================================================#

# Cloud
[[tooltips]]
  tips = ["aws","terraform"]
  type = "aws"
  style = "diamond"
  leading_diamond = ""
  trailing_diamond = ""
  foreground = "p:white"
  background = "p:orange_aws"
  template = " {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} "

  [tooltips.properties]
    display_default = true

[[tooltips]]
  tips = ["az", "terraform"]
  type = "az"
  style = "diamond"
  leading_diamond = ""
  trailing_diamond = ""
  foreground = "p:white"
  background = "p:blue_azure"
  template = "  {{ .Name }} "

  [tooltips.properties]
    display_default = true

# Orchestration
[[tooltips]]
  tips = [ "docker", "d" ]
  type = "docker"
  style = "diamond"
  leading_diamond = ""
  trailing_diamond = ""
  foreground = "p:white"
  background = "p:blue_docker"
  template = "  {{ .Context }} "

[[tooltips]]
  type = "helm"
  style = "diamond"
  leading_diamond = ""
  trailing_diamond = ""
  foreground = "p:white"
  background = "p:blue_helm"
  template = " {{ .Version }} "

  [tooltips.properties]
    display_mode = "always"

[[tooltips]]
  tips = [ "kubectl", "k" ]
  type = "kubectl"
  style = "diamond"
  leading_diamond = ""
  trailing_diamond = ""
  foreground = "p:white"
  background = "p:blue_kube"
  template = " ﴱ {{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}} "

  [tooltips.properties]
    display_error = true
    parse_kubeconfig = true

