- name: APT
  hosts: all
  gather_facts: false
  vars:
    packages:
      - bash-completion
      - bat
      - build-essential
      - curl
      - fzf # general-purpose command-line fuzzy finder
      - git
      - htop # resources monitoring
      - jq # command-line JSON processor
      - libsecret-1-0 # Bitwarden CLI requirement
      - net-tools
      - pwgen # random password generator
      - software-properties-common
      - tzdata # timezone
      - unzip
      - vim # text editor of choice
      - xclip # CLI clipboard utility
      - zip

  tasks:
  # Packages
  - name: Packages
    block:

    # sudo apt update -y
    - name: Update cache
      tags: [init, update]
      ansible.builtin.apt:
        update_cache: true

    - name: List packages
      tags: [init, update]
      ansible.builtin.debug:
        msg: "packages: {{ packages }}"

    # sudo apt install -y
    - name: Install packages
      tags: init
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present

    # sudo apt remove -y
    # - name: Remove packages
    #   tags: init
    #   ansible.builtin.apt:
    #     name:
    #       -
    #     state: absent

    # sudo apt upgrade -y
    - name: Upgrade packages
      tags: update
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: latest

  # Cleaning
  - name: Cleaning
    tags: clean
    block:

    # apt autoclean
    - name: Cleans the local repository of package files that can no longer be downloaded
      ansible.builtin.apt:
        autoclean: true

    # apt autoremove
    - name: Remove unused dependencies
      ansible.builtin.apt:
        autoremove: true

  # fzf
  - name: fzf
    tags: [init, update]
    block:

    - name: fzf - Download completion and key-bindings
      ansible.builtin.uri:
        method: GET
        url: https://raw.githubusercontent.com/junegunn/fzf/refs/heads/master/shell/{{ item }}
        dest: /usr/share/doc/fzf/examples/{{ item }}
        follow_redirects: safe
      loop:
       - completion.bash
       - completion.zsh
       - key-bindings.bash
       - key-bindings.zsh
