- name: APT
  hosts: all
  gather_facts: false
  vars_files:
    - ../vars/main.yml

  tasks:
  # Repositories
  - name: Repositories
    tags: init
    block:

    - name: List repositories
      ansible.builtin.debug:
        msg: "Repositories: {{ apt_repositories }}"

    # add-apt-repository
    - name: Add repositories
      become: true
      ansible.builtin.apt_repository:
        repo: "{{ item }}"
      loop: "{{ apt_repositories }}"

  # Packages
  - name: Packages
    tags: [init, update]
    ansible.builtin.include_tasks:
      file: ../tasks/packages.yml
    vars:
      package_list: "{{ apt_packages }}"

  # Cleaning
  - name: Cleaning
    tags: clean
    block:

    # apt autoclean
    - name: Cleans the local repository of package files that can no longer be downloaded
      ansible.builtin.apt:
        autoclean: true

    # apt autoremove
    - name: Remove unused dependencies
      ansible.builtin.apt:
        autoremove: true
