- name: APT
  hosts: all
  gather_facts: false
  vars_files:
    - ../vars/main.yml

  tasks:
  # -------------------------------------------------------------------------- #
  #               ------- Repositories ------
  # -------------------------------------------------------------------------- #
  - name: Repositories
    tags: init
    block:

    - name: List repositories
      ansible.builtin.debug:
        msg: "Repositories: {{ apt_repositories }}"

    # add-apt-repository
    - name: Add repositories
      ansible.builtin.apt_repository:
        repo: "{{ item }}"
      loop: "{{ apt_repositories }}"

  # -------------------------------------------------------------------------- #
  #               ------- Packages ------
  # -------------------------------------------------------------------------- #
  - name: Packages
    block:

    # sudo apt update -y
    - name: Update cache
      tags: [init, update]
      ansible.builtin.apt:
        update_cache: true

    - name: Show packages
      tags: [init, update]
      ansible.builtin.debug:
        msg: "Packages: {{ apt_packages }}"

    # sudo apt install -y
    - name: Install packages
      tags: init
      ansible.builtin.apt:
        name: "{{ apt_packages }}"
        state: present

    # sudo apt remove -y
    # - name: Remove packages
    #   tags: init
    #   ansible.builtin.apt:
    #     name:
    #       -
    #     state: absent

    # sudo apt upgrade -y
    - name: Upgrade packages
      tags: update
      ansible.builtin.apt:
        name: "{{ apt_packages }}"
        state: latest

  # -------------------------------------------------------------------------- #
  #               ------- Cleaning ------
  # -------------------------------------------------------------------------- #
  - name: Cleaning
    tags: clean
    block:

    # apt autoclean
    - name: Cleans the local repository of package files that can no longer be downloaded
      ansible.builtin.apt:
        autoclean: true

    # apt autoremove
    - name: Remove unused dependencies
      ansible.builtin.apt:
        autoremove: true
