- name: APT
  hosts: all
  gather_facts: false
  vars:
    packages:
      - apache2-utils # htpasswd utility
      - bash-completion
      - bat
      - build-essential
      - cmake
      - curl
      - fzf # general-purpose command-line fuzzy finder
      - gdal-bin # executable to use GDAL with Python
      - git # gold standard version control system
      - git-filter-repo # Quickly rewrite git repository history (filter-branch replacement)
      - htop # resources monitoring
      - jq # command-line JSON processor
      - libbz2-dev # data compression library to develop with Python
      - libgdal-dev # library to use GDAL with Python
      - libpq-dev # library to develop with PostgreSQL
      - man-db # man pages
      - net-tools
      - nfs-common
      - ninja-build
      - pdftk
      - pwgen # random password generator
      - software-properties-common
      - ssh
      - trippy # network diagnostic tool
      - tzdata # timezone
      - unzip
      - vim # text editor of choice
      - xclip # CLI clipboard utility
      - zip
    repositories:
      - ppa:fujiapple/trippy

  tasks:
  # Repositories
  - name: Repositories
    tags: init
    block:

    - name: List repositories
      ansible.builtin.debug:
        msg: "packages: {{ repositories }}"

    # add-apt-repository
    - name: Add repositories
      ansible.builtin.apt_repository:
        repo: "{{ item }}"
      loop: "{{ repositories }}"

  # Packages
  - name: Packages
    block:

    # sudo apt update -y
    - name: Update cache
      tags: [init, update]
      ansible.builtin.apt:
        update_cache: true

    - name: List packages
      tags: [init, update]
      ansible.builtin.debug:
        msg: "packages: {{ packages }}"

    # sudo apt install -y
    - name: Install packages
      tags: init
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present

    # sudo apt remove -y
    # - name: Remove packages
    #   tags: init
    #   ansible.builtin.apt:
    #     name:
    #       -
    #     state: absent

    # sudo apt upgrade -y
    - name: Upgrade packages
      tags: update
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: latest

  # Cleaning
  - name: Cleaning
    tags: clean
    block:

    # apt autoclean
    - name: Cleans the local repository of package files that can no longer be downloaded
      ansible.builtin.apt:
        autoclean: true

    # apt autoremove
    - name: Remove unused dependencies
      ansible.builtin.apt:
        autoremove: true

  # fzf
  - name: fzf
    tags: [init, update]
    block:

    - name: fzf - Download completion and key-bindings
      ansible.builtin.uri:
        method: GET
        url: https://raw.githubusercontent.com/junegunn/fzf/refs/heads/master/shell/{{ item }}
        dest: /usr/share/doc/fzf/examples/{{ item }}
        follow_redirects: safe
      loop:
       - completion.bash
       - completion.zsh
       - key-bindings.bash
       - key-bindings.zsh
