- name: Homebrew
  hosts: all
  gather_facts: false
  vars_files:
    - ../vars/main.yml

  tasks:
  - name: Homebrew
    tags: [init, update]
    block:

    # Dependencies
    - name: Dependencies
      ansible.builtin.include_tasks:
        file: ../tasks/packages.yml
      vars:
        package_list: "{{ homebrew_dependencies }}"
        package_type: dependencies

    # Installation
    # /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - name: Installation
      ansible.builtin.include_tasks:
        file: ../tasks/script.yml
      vars:
        url: "{{ homebrew_install_url }}"
        cmd: /bin/bash -c /tmp/install.sh

    # Formulas
    - name: Formulas
      ansible.builtin.include_tasks:
        file: ../tasks/formulas.yml
      vars:
        formulas: "{{ homebrew_formulas }}"
