- name: Homebrew
  hosts: all
  gather_facts: true
  vars_files:
    - ../vars/main.yml

  tasks:
  # -------------------------------------------------------------------------- #
  #               ------- Dependencies ------
  # -------------------------------------------------------------------------- #
  - name: Dependencies
    block:

    - name: Show dependencies
      tags: [init, update]
      ansible.builtin.debug:
        msg: "Dependencies: {{ homebrew_dependencies }}"

    # sudo apt update -y && sudo apt install -y
    - name: Install dependencies
      tags: init
      ansible.builtin.apt:
        name: "{{ homebrew_dependencies }}"
        state: present
        update_cache: true

    # sudo apt update -y && sudo apt upgrade -y
    - name: Upgrade dependencies
      tags: update
      ansible.builtin.apt:
        name: "{{ homebrew_dependencies }}"
        state: latest
        update_cache: true

  # -------------------------------------------------------------------------- #
  #               ------- Homebrew ------
  # -------------------------------------------------------------------------- #
  - name: Homebrew
    tags: [init, update]
    become_user: "{{ ansible_user_id }}"
    block:

    - name: Download install script
      ansible.builtin.uri:
        method: GET
        url: "{{ homebrew_install_url }}"
        dest: "/tmp/homebrew_install.sh"
        follow_redirects: safe
        mode: 0700

    - name: Run install script
      ansible.builtin.command:
        cmd: /bin/bash -c /tmp/homebrew_install.sh
      register: install_result
      changed_when: install_result.rc == 0

    - name: Remove install script
      ansible.builtin.file:
        path: "/tmp/homebrew_install.sh"
        state: absent

  # -------------------------------------------------------------------------- #
  #               ------- Formulas ------
  # -------------------------------------------------------------------------- #
  - name: Formulas
    become_user: "{{ ansible_user_id }}"
    block:

    - name: Show formulas
      tags: [init, update]
      ansible.builtin.debug:
        msg: "Formulas: {{ homebrew_formulas }}"

    # brew install
    - name: Install formulas
      tags: init
      community.general.homebrew:
        name: "{{ homebrew_formulas }}"
        state: present
        update_homebrew: true

    # brew upgrade
    - name: Upgrade formulas
      tags: update
      community.general.homebrew:
        name: "{{ homebrew_formulas }}"
        state: latest
        update_homebrew: true
