- name: Eza
  hosts: all
  gather_facts: true
  vars_files:
    - ../vars/main.yml

  tasks:
  # -------------------------------------------------------------------------- #
  #               ------- Dependencies ------
  # -------------------------------------------------------------------------- #
  - name: Dependencies
    block:

    - name: Show dependencies
      tags: [init, update]
      ansible.builtin.debug:
        msg: "Dependencies: {{ eza_dependencies }}"

    # sudo apt update -y && sudo apt install -y
    - name: Install dependencies
      tags: init
      ansible.builtin.apt:
        name: "{{ eza_dependencies }}"
        state: present
        update_cache: true

    # sudo apt update -y && sudo apt upgrade -y
    - name: Upgrade dependencies
      tags: update
      ansible.builtin.apt:
        name: "{{ eza_dependencies }}"
        state: latest
        update_cache: true

  # -------------------------------------------------------------------------- #
  #               ------- Repository ------
  # -------------------------------------------------------------------------- #
  - name: Repository
    tags: init
    block:

    - name: Create /etc/apt/keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: 0755

    # curl -fsSL https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor --output /etc/apt/keyrings/gierens.gpg
    - name: Download GPG apt key
      ansible.builtin.uri:
        method: GET
        url: https://raw.githubusercontent.com/eza-community/eza/main/deb.asc
        dest: /tmp/deb.asc
        follow_redirects: safe
        mode: 0644

    - name: Import GPG key
      ansible.builtin.command:
        cmd: gpg --dearmor --output /etc/apt/keyrings/gierens.gpg --yes /tmp/deb.asc

    # echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/gierens.gpg] stable main" | sudo tee /etc/apt/sources.list.d/gierens.list > /dev/null
    - name: Add apt repository
      ansible.builtin.apt_repository:
        repo: deb [arch={{ deb_architecture[ansible_architecture] }} signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main

    - name: Remove temporary GPG key
      ansible.builtin.file:
        path: /tmp/deb.asc
        state: absent

  # -------------------------------------------------------------------------- #
  #               ------- Packages ------
  # -------------------------------------------------------------------------- #
  - name: Packages
    block:

    - name: Show packages
      tags: [init, update]
      ansible.builtin.debug:
        msg: "Packages: {{ eza_packages }}"

    # sudo apt update -y && sudo apt install -y
    - name: Install packages
      tags: init
      ansible.builtin.apt:
        name: "{{ eza_packages }}"
        state: present
        update_cache: true

    # sudo apt update -y && sudo apt upgrade -y
    - name: Upgrade packages
      tags: update
      ansible.builtin.apt:
        name: "{{ eza_packages }}"
        state: latest
        update_cache: true

  # -------------------------------------------------------------------------- #
  #               ------- Version ------
  # -------------------------------------------------------------------------- #
  - name: Version
    tags: [init, update]
    block:

    - name: Confirm version
      ansible.builtin.command:
        cmd: eza --version
      register: version
      changed_when: false

    - name: Show version
      when: version is defined
      ansible.builtin.debug:
        msg: "Installed version: {{ version.stdout }}"
