- name: Eza
  hosts: all
  gather_facts: true
  vars_files:
    - ../vars/main.yml

  tasks:
  # Dependencies
  - name: Dependencies
    tags: [init, update]
    ansible.builtin.include_tasks:
      file: ../tasks/packages.yml
    vars:
      package_list: "{{ eza_dependencies }}"
      package_type: dependencies

  # Repository
  # curl -fsSL https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor --output /etc/apt/keyrings/gierens.gpg
  # echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/gierens.gpg] stable main" | sudo tee /etc/apt/sources.list.d/gierens.list > /dev/null
  - name: Repository
    tags: init
    ansible.builtin.include_tasks:
      file: ../tasks/repository.yml
    vars:
      key_url: https://raw.githubusercontent.com/eza-community/eza/main/deb.asc
      key_output: /etc/apt/keyrings/gierens.gpg
      repository: "deb [arch={{ deb_architecture[ansible_architecture] }} signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main"

  # Packages
  - name: Packages
    tags: [init, update]
    ansible.builtin.include_tasks:
      file: ../tasks/packages.yml
    vars:
      package_list: "{{ eza_packages }}"

  # Version
  - name: Version
    tags: [init, update]
    ansible.builtin.include_tasks:
      file: ../tasks/version.yml
    vars:
      cmd: eza --version
