- name: Eza
  hosts: all
  gather_facts: true
  vars:
    dependencies:
      - gpg
    packages:
      - eza
  vars_files:
    - ../vars/main.yml

  tasks:
  # Dependencies
  - name: Dependencies
    block:

    - name: List dependencies
      tags: [init, update]
      ansible.builtin.debug:
        msg: "dependencies: {{ dependencies }}"

    # sudo apt update -y && sudo apt install -y
    - name: Install dependencies
      tags: init
      ansible.builtin.apt:
        name: "{{ dependencies }}"
        state: present
        update_cache: true

    # sudo apt update -y && sudo apt upgrade -y
    - name: Upgrade dependencies
      tags: update
      ansible.builtin.apt:
        name: "{{ dependencies }}"
        state: latest
        update_cache: true

  # Repository
  - name: Repository
    tags: init
    block:

    - name: Create /etc/apt/keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: 0755

    - name: Download GPG apt key
      ansible.builtin.uri:
        method: GET
        url: https://raw.githubusercontent.com/eza-community/eza/main/deb.asc
        dest: /tmp/deb.asc
        follow_redirects: safe
        mode: 0644

    - name: Import GPG key
      ansible.builtin.command:
        cmd: gpg --dearmor -o /etc/apt/keyrings/gierens.gpg /tmp/deb.asc

    - name: Add apt repository
      ansible.builtin.apt_repository:
        repo: deb [arch={{ deb_architecture[ansible_architecture] }} signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main

  # Packages
  - name: Packages
    block:

    - name: List packages
      tags: [init, update]
      ansible.builtin.debug:
        msg: "packages: {{ packages }}"

    # sudo apt update -y && sudo apt install -y
    - name: Install
      tags: init
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true

    # sudo apt update -y && sudo apt upgrade -y
    - name: Upgrade
      tags: update
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: latest
        update_cache: true

  # Version
  - name: Version
    tags: [init, update]
    block:

    - name: Confirm version
      ansible.builtin.command:
        cmd: eza --version
      register: version
      changed_when: false

    - name: Show version
      when: version is defined
      ansible.builtin.debug:
        msg: "Installed version: {{ version.stdout }}"
