- name: Fzf
  hosts: all
  gather_facts: false

  tasks:
  # -------------------------------------------------------------------------- #
  #               ------- Completions & Key Bindings ------
  # -------------------------------------------------------------------------- #
  - name: Completions & Key Bindings
    tags: [init, update]
    block:

    - name: Download completion and key-bindings
      ansible.builtin.uri:
        method: GET
        url: https://raw.githubusercontent.com/junegunn/fzf/refs/heads/master/shell/{{ item }}
        dest: /usr/share/doc/fzf/examples/{{ item }}
        follow_redirects: safe
      loop:
      - completion.bash
      - completion.zsh
      - key-bindings.bash
      - key-bindings.zsh
