- name: Oh My Posh
  hosts: all
  gather_facts: false
  vars_files:
    - ../vars/main.yml

  tasks:
  # Installation
  # curl -s https://ohmyposh.dev/install.sh | bash -s
  - name: Installation
    tags: [init, update]
    ansible.builtin.include_tasks:
      file: ../tasks/script.yml
    vars:
      url: "{{ omp_install_url }}"
      cmd: /bin/bash /tmp/install.sh -d ~/.local/bin

  # Version
  - name: Version
    tags: [init, update]
    ansible.builtin.include_tasks:
      file: ../tasks/version.yml
    vars:
      cmd: ~/.local/bin/oh-my-posh version
