- name: Zoxide
  hosts: all
  gather_facts: false
  vars_files:
    - ../vars/main.yml

  tasks:
  # -------------------------------------------------------------------------- #
  #               ------- Installation ------
  # -------------------------------------------------------------------------- #
  - name: Zoxide
    become_user: ubuntu
    tags: [init, update]
    block:

    - name: Download install script
      ansible.builtin.uri:
        method: GET
        url: "{{ zoxide_install_url }}"
        dest: "/tmp/zoxide_install.sh"
        follow_redirects: safe
        mode: 0700

    - name: Run install script
      ansible.builtin.command:
        cmd: /bin/sh -c /tmp/zoxide_install.sh
      register: install_result
      changed_when: install_result.rc == 0

    - name: Remove install script
      ansible.builtin.file:
        path: "/tmp/zoxide_install.sh"
        state: absent

    # ------------------------------------------------------------------------ #
    #               ------- Version ------
    # ------------------------------------------------------------------------ #
    always:
    - name: Confirm version
      ansible.builtin.command:
        cmd: ~/.local/bin/zoxide --version
      register: version
      changed_when: false

    - name: Show version
      when: version is defined
      ansible.builtin.debug:
        msg: "Installed version: {{ version.stdout }}"
