- name: Zsh
  hosts: all
  gather_facts: false
  vars:
    antigen_url: git.io/antigen
    dependencies:
      - curl
      - git
      - zsh

  tasks:
  # Dependencies
  - name: Dependencies
    block:

    - name: List dependencies
      tags: [init, update]
      ansible.builtin.debug:
        msg: "dependencies: {{ dependencies }}"

    # sudo apt update -y && sudo apt install -y
    - name: Install dependencies
      tags: init
      ansible.builtin.apt:
        name: "{{ dependencies }}"
        state: present
        update_cache: true

    # sudo apt update -y && sudo apt upgrade -y
    - name: Upgrade dependencies
      tags: update
      ansible.builtin.apt:
        name: "{{ dependencies }}"
        state: latest
        update_cache: true

  # Shell
  - name: Shell - Set zsh as default
    tags: init
    ansible.builtin.user:
      name: ubuntu
      shell: /bin/zsh

  # Package Manger - Antigen
  # curl -L git.io/antigen > /usr/local/bin/antigen.zsh
  - name: Antigen - Install
    tags: [init, update]
    ansible.builtin.uri:
      method: GET
      url: "{{ antigen_url }}"
      follow_redirects: safe
      dest: "/usr/local/bin/antigen.zsh"
      mode: 0755
