- name: Zsh
  hosts: all
  gather_facts: false
  vars_files:
    - ../vars/main.yml

  tasks:
  # Dependencies
  - name: Dependencies
    block:

    - name: List dependencies
      tags: [init, update]
      ansible.builtin.debug:
        msg: "dependencies: {{ zsh_dependencies }}"

    # sudo apt update -y && sudo apt install -y
    - name: Install dependencies
      tags: init
      ansible.builtin.apt:
        name: "{{ zsh_dependencies }}"
        state: present
        update_cache: true

    # sudo apt update -y && sudo apt upgrade -y
    - name: Upgrade dependencies
      tags: update
      ansible.builtin.apt:
        name: "{{ zsh_dependencies }}"
        state: latest
        update_cache: true

  # Shell
  - name: Set zsh as default shell
    tags: init
    ansible.builtin.user:
      name: ubuntu
      shell: /bin/zsh

  # Package Manager - Antidote
  # git clone --depth=1 https://github.com/mattmc3/antidote.git ${ZDOTDIR:-$HOME}/antidote
  - name: Antidote
    become_user: ubuntu
    block:

    - name: Antidote - Install
      tags: [init, update]
      ansible.builtin.git:
        repo: https://github.com/mattmc3/antidote.git
        dest: /home/ubuntu/.local/antidote
        depth: 1
