- name: Pulumi
  hosts: all
  gather_facts: false
  vars:
    install_tmp: /tmp/pulumi
    install_url: https://get.pulumi.com

  tasks:
  # Pulumi
  - name: Pulumi
    become_user: ubuntu
    tags: [init, update]
    block:

    - name: Create temporary directory
      ansible.builtin.file:
        path: "{{ install_tmp }}"
        state: directory
        mode: 0700

    - name: Download install script
      ansible.builtin.uri:
        method: GET
        url: "{{ install_url }}"
        dest: "{{ install_tmp }}/get.pulumi.com"
        follow_redirects: safe
        mode: 0700

    - name: Install
      ansible.builtin.command:
        cmd: /bin/sh -c {{ install_tmp }}/get.pulumi.com
      register: install_result
      changed_when: install_result.rc == 0

    - name: Remove temporary directory
      ansible.builtin.file:
        path: "{{ install_tmp }}"
        state: absent

    # Version
    always:
    - name: Confirm version
      tags: [init, update]
      ansible.builtin.command:
        cmd: ~/.pulumi/bin/pulumi version
      register: version
      changed_when: false

    - name: Show version
      tags: [init, update]
      when: version is defined
      ansible.builtin.debug:
        msg: "Installed version: {{ version.stdout }}"
