- name: Chocolatey
  hosts: all
  gather_facts: false
  vars:
    excluded_packages:
      - docker-engine
      - git
      - git.install
      - vscode
      - vscode.install
      - vscodium
      - vscodium.install

  tasks:
  # Packages
  - name: Packages
    block:

    - name: Read Chocolatey config XML file content from control node
      tags: [init, update]
      ansible.builtin.set_fact:
        packages_config: "{{ lookup('file', '$HOME/.config/chocolatey/packages.config') }}"

    - name: Parse XML content
      tags: [init, update]
      community.general.xml:
        xmlstring: "{{ packages_config }}"
        xpath: /packages/package
        content: attribute
      register: packages_params

    - name: Extract packages
      tags: [init, update]
      ansible.builtin.set_fact:
        packages: "{{ packages_params.matches | map(attribute='id') | difference(excluded_packages) | list }}"

    - name: List packages
      tags: [init, update]
      ansible.builtin.debug:
        msg: "packages: {{ packages }}"

    # choco install -y
    - name: Install packages
      tags: init
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ packages }}"
        state: present

    # choco uninstall -y
    # - name: Remove packages
    #   tags: init
    #   chocolatey.chocolatey.win_chocolatey:
    #     name:
    #       -
    #     state: absent

    # choco upgrade -y
    - name: Upgrade packages
      tags: update
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ packages }}"
        state: latest

  # Docker
  - name: Docker
    block:

    # choco install -y docker-engine
    - name: Install Docker
      tags: init
      chocolatey.chocolatey.win_chocolatey:
        name: docker-engine
        package_params: "/DockerGroup:docker /StartService"
        pinned: true
        version: "24.0.7"
        state: present

    # choco upgrade -y docker-engine
    # - name: Upgrade Docker
    #   tags: update
    #   chocolatey.chocolatey.win_chocolatey:
    #     name: docker-engine
    #     package_params: "/DockerGroup:docker /StartService"
    #     state: latest

  # Git
  - name: Git
    block:

    # choco install -y git git.install
    - name: Install Git
      tags: init
      chocolatey.chocolatey.win_chocolatey:
        name:
          - git
          - git.install
        package_params: "/NoAutoCrlf /WindowsTerminal /DefaultBranchName:main"
        state: present

    # choco upgrade -y git git.install
    - name: Upgrade Git
      tags: update
      chocolatey.chocolatey.win_chocolatey:
        name:
          - git
          - git.install
        state: latest

  # Visual Studio Code
  - name: Visual Studio Code
    block:

    # choco install -y vscode vscode.install
    - name: Install Visual Studio Code
      tags: init
      chocolatey.chocolatey.win_chocolatey:
        name:
          - vscode
          - vscode.install
        package_params: "/NoDesktopIcon"
        state: present

    # choco upgrade -y vscode vscode.install
    - name: Upgrade Visual Studio Code
      tags: update
      chocolatey.chocolatey.win_chocolatey:
        name:
          - vscode
          - vscode.install
        state: latest

  # VSCodium
  # - name: VSCodium
  #   block:

  #   # choco install -y vscodium vscodium.install
  #   - name: Install VSCodium
  #     tags: init
  #     chocolatey.chocolatey.win_chocolatey:
  #       name:
  #         - vscodium
  #         - vscodium.install
  #       package_params: "/AssociateWithFiles /NoDesktopIcon"
  #       state: present

  #   # choco upgrade -y vscodium vscodium.install
  #   - name: Upgrade VSCodium
  #     tags: update
  #     chocolatey.chocolatey.win_chocolatey:
  #       name:
  #         - vscodium
  #         - vscodium.install
  #       state: latest

  # Configuration
  - name: Configuration
    tags: [init, update]
    block:

    - name: Update configuration
      ansible.windows.win_powershell:
      script: |
        $OUTPUT_FILE_PATH = "$HOME/.config/chocolatey/packages.config"
        choco export -y --include-version-numbers --output-file-path="$OUTPUT_FILE_PATH"

    - name: Remove configuration backup
      ansible.windows.win_file module:
        path: "$HOME/.config/chocolatey/packages.config.backup"
        state: absent

    - name: Fetch configuration
      ansible.builtin.fetch module:
        src: "$HOME/.config/chocolatey/packages.config"
        dest: "$HOME/.config/chocolatey/"
        flat: true
